services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: mobilefrost_user
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: mobilefrost_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    # Port 5432 MUSS freigegeben sein, damit Dein lokales
    # Windows-Python-Skript die Daten hineinschreiben kann.
    ports:
      - "5432:5432" 

volumes:
  pgdata: